version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install

  pre_build: 
    commands: 
      - echo "Preparing for build"

  build:
    commands:
      - echo "Running tests..."
      - npm test

  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files:
    - "**/*"
